# Generated by Django 3.1.3 on 2020-11-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch_office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True, verbose_name='Codigo')),
                ('name', models.CharField(max_length=40, verbose_name='Nombre')),
                ('address', models.CharField(max_length=60, verbose_name='Direccion')),
                ('phone', models.CharField(max_length=10, unique=True, verbose_name='Telefono')),
            ],
        ),
    ]
