# Generated by Django 3.1.3 on 2020-11-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_auto_20201128_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True, verbose_name='Codigo del Hotel')),
                ('name', models.CharField(max_length=40, verbose_name='Nombre')),
                ('address', models.CharField(max_length=60, verbose_name='Direccion')),
                ('city', models.CharField(max_length=30, verbose_name='Ciudad')),
                ('phone', models.CharField(max_length=10, unique=True, verbose_name='Telefono')),
                ('square', models.CharField(max_length=50, verbose_name='Plaza')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hoteles',
            },
        ),
        migrations.AlterField(
            model_name='branch_office',
            name='code',
            field=models.CharField(max_length=6, unique=True, verbose_name='Codigo de la Sucursal'),
        ),
    ]
