# Generated by Django 3.1.3 on 2020-11-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0003_auto_20201128_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True, verbose_name='Coidgo del Turista')),
                ('name', models.CharField(max_length=40, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('address', models.CharField(max_length=60, verbose_name='Direccion')),
                ('phone', models.CharField(max_length=10, unique=True, verbose_name='Telefono')),
            ],
            options={
                'verbose_name': 'Turista',
                'verbose_name_plural': 'Turistas',
            },
        ),
    ]
