# Generated by Django 3.1.3 on 2020-11-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0006_stay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tourist_flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='Codigo Vuelo de Turista')),
                ('passenger_class', models.CharField(max_length=25, verbose_name='Clase de pasajero')),
            ],
            options={
                'verbose_name': 'Vuelo de Turista',
                'verbose_name_plural': 'Vuelos de Turistas',
            },
        ),
        migrations.AlterField(
            model_name='stay',
            name='code',
            field=models.CharField(max_length=8, unique=True, verbose_name='Codigo de Estancia'),
        ),
    ]
