# Generated by Django 3.1.3 on 2020-12-03 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0009_auto_20201128_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='stay',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='travels.hotel', verbose_name='Hotel'),
            preserve_default=False,
        ),
    ]
