# Generated by Django 3.1.3 on 2020-12-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0010_stay_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourist_flight',
            name='nacionality',
            field=models.CharField(choices=[('MX', 'México'), ('CO', 'Colombia'), ('EUA', 'Estados Unidos'), ('ES', 'España')], default='MX', max_length=100),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='code',
            field=models.CharField(max_length=6, unique=True, verbose_name='Codigo del Turista'),
        ),
    ]
