# Generated by Django 3.1.3 on 2020-12-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0011_auto_20201203_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourist_flight',
            name='nacionality',
        ),
        migrations.RemoveField(
            model_name='tourist_flight',
            name='passenger_class',
        ),
        migrations.AddField(
            model_name='tourist_flight',
            name='passenger',
            field=models.CharField(choices=[('PRIMERA CLASE', 'PRIMERA CLASE'), ('Business', 'Clase ejecutiva o business'), ('Premium', 'Clase premium economy'), ('Económica', 'Clase turista o económica')], default='PRIMERA CLASE', max_length=100),
        ),
    ]
