# Generated by Django 3.1.3 on 2020-12-03 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0012_auto_20201203_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourist_flight',
            name='flight',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='travels.flight', verbose_name='Vuelo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tourist_flight',
            name='passenger',
            field=models.CharField(choices=[('Primera clase', 'Pimera clase'), ('Business', 'Clase ejecutiva o business'), ('Premium', 'Clase premium economy'), ('Económica', 'Clase turista o económica')], default='Primera clase', max_length=100),
        ),
    ]
