# Generated by Django 3.1.3 on 2020-12-03 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0013_auto_20201203_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourist_flight',
            name='flight',
        ),
    ]
