# Generated by Django 3.1.3 on 2020-12-03 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0014_remove_tourist_flight_flight'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourist_flight',
            name='flight',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='travels.flight', verbose_name='Vuelo'),
            preserve_default=False,
        ),
    ]
