# Generated by Django 3.1.3 on 2020-12-04 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0016_auto_20201203_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourist_flight',
            name='flight',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='travels.flight', verbose_name='Turista'),
            preserve_default=False,
        ),
    ]
