# Generated by Django 3.1.3 on 2020-12-04 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0017_tourist_flight_flight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='tourist',
        ),
        migrations.RemoveField(
            model_name='tourist_flight',
            name='flight',
        ),
    ]
