# Generated by Django 3.1.3 on 2020-12-04 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0019_tourist_flight_flight'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourist_flight',
            name='reserve',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='travels.reserve', verbose_name='Reserva'),
            preserve_default=False,
        ),
    ]
