# Generated by Django 3.1.3 on 2020-12-04 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0020_tourist_flight_reserve'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='branch_office',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='travels.branch_office', verbose_name='Sucursal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserve',
            name='stay',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='travels.stay', verbose_name='Estancia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserve',
            name='tourist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='travels.tourist', verbose_name='Turista'),
            preserve_default=False,
        ),
    ]
